### ISSUE TITLE
可否发送一份AppTrackingTransparency.framework给我

### ISSUE THREAD

**Issue by FontiOS** [guojunliu/XYDeviceInfo#1]
邮箱：czljcb@163.com，万分感觉

**Comment by guojunliu** [comment]
已发送，如果你本地安装了Xcode 12beta，在此路径下可以找到AppTrackingTransparency

/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AppTrackingTransparency.framework
